# Generated by Django 3.0.5 on 2020-07-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20200707_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='id_challenge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
    ]
